# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_nn <- function(board) {
    .Call('c4dougbot2000_get_nn', PACKAGE = 'c4dougbot2000', board)
}

get_lengths <- function(board, target) {
    .Call('c4dougbot2000_get_lengths', PACKAGE = 'c4dougbot2000', board, target)
}

get_top <- function(board) {
    .Call('c4dougbot2000_get_top', PACKAGE = 'c4dougbot2000', board)
}

